version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      # - ./app:/app
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
  # env_file:
  #   - .env